name: Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aussiebroadwan/tony
  CONTAINER_NAME: tab-tony

jobs:

  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to the Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name}}


  deploy:
    runs-on: deploy
    steps:

    # Login to the Docker registry
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Pull the Docker image
    - name: Pull ${{ github.ref_name}}
      run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name}}
    
    # Stop the existing container
    - name: Stop Existing Container
      run: docker stop ${{ env.CONTAINER_NAME }} || true

    # Deploy the Docker image
    - name: Deploy ${{ github.ref_name}}
      run: docker run --name=${{ env.CONTAINER_NAME }} -d -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -e DISCORD_SERVER_ID=${{ secrets.DISCORD_SERVER_ID }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name}}
