name: Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aussiebroadwan/tony

jobs:

  deploy:
    runs-on: deploy

    steps:
    - name: Deploy Latest
      run: docker run -d -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -e DISCORD_SERVER_ID={{ $DISCORD_SERVER_ID }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
