name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: apt-get update && apt-get install -y gcc
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: CGO_ENABLED=1 go test ./...